### PR TITLE
fix(bal-number-input): allow decimal point for de, be and lu

### LINKED ISSUE #978: [bal-number-input] - region german does not allow decimal point entries
It isn't possible to input correct decimal numbers, if the bal-number-input tag is used with German settings

## Detailed description

If the _bal-number-input_ tag is used with german settings and we try to input a decimal number e.g. **1234,56**, then the input field shows **1234,00**.

## Steps to reproduce the issue

1. Use german settings for the baloise component system configuration: 
- Region: de
- Language: DE
2. Declare the _bal-number-input_ field
4. Try to input: **1234,56**
5. The input field shows: **1234,00**

## Additional information

image

### PR DESCRIPTION
**Pull request by mladenplaninicic**
Closes #

{{short description}}

## Acceptance Criteria

- [ ] Design Review by @Gagne87, @clastzoo
- [ ] Technical Review by @hirsch88, @mladenplaninicic, @nobilo
- [ ] [Style Guide](https://stenciljs.com/docs/style-guide) Review @hirsch88, @mladenplaninicic, @nobilo
- [ ] Visual test done by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
- [ ] Functional test done by @hirsch88, @nobilo, @mladenplaninicic
- Browser Testing by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
    - Desktop
        - [ ] Chrome
        - [ ] Edge
        - [ ] Safari
        - [ ] Firefox
    - Tablet
        - [ ] iPad (Landscape / Portrait)
    - Mobile
        - [ ] Safari iOS
        - [ ] Chrome Preview

### CODE REVIEW

File: packages/components/src/components/form/bal-number-input/bal-number-input.tsx [hunk 1]
```diff
@@ -242,7 +242,12 @@ export class NumberInput implements ComponentInterface, BalConfigObserver, FormI
   private onInput = (ev: Event) => {
     const input = getInputTarget(ev)
     if (input) {
-      const parsedValue = parseFloat(parseFloat(input.value).toFixed(this.decimal))
+      let parsedValue = 0
+      if (this.region === 'CH') {
+        parsedValue = parseFloat(parseFloat(input.value).toFixed(this.decimal))
+      } else {
+        parsedValue = parseFloat(input.value.replace(',', '.'))
+      }
```
Comment (hirsch88) [inline packages/components/src/components/form/bal-number-input/bal-number-input.tsx]:
```typescript
const parsedValue = parseFloat(parseFloat(parseFloatString(input.value)).toFixed(this.decimal))


private parseFloatString = (value : string): string => {
  return value.replace(getDecimalSeparator(), '.')
}
```

File: packages/components/src/components/form/bal-number-input/bal-number-input.tsx [hunk 2]
```diff
@@ -312,14 +317,18 @@ export class NumberInput implements ComponentInterface, BalConfigObserver, FormI
...
-    const value = this.hasFocus ? this.getRawValue() : this.getFormattedValue()
+    let value = this.hasFocus ? this.getRawValue() : this.getFormattedValue()
     const labelId = this.inputId + '-lbl'
     const label = findItemLabel(this.el)
     if (label) {
       label.id = labelId
       label.htmlFor = this.inputId
     }
 
+    if (this.region !== 'CH' && this.hasFocus) {
```
Comment (hirsch88) [inline packages/components/src/components/form/bal-number-input/bal-number-input.tsx]:
```typescript
const value = this.hasFocus ? parseFloatString(this.getRawValue()) : this.getFormattedValue()
```

**Review by hirsch88 — APPROVED** [review]
