### PR TITLE
fix(bal-tabs): create separate numberation for o-tabs

### LINKED ISSUE #686: [bal-tabs] Numeration of tabs for o-steps is wrong
As stated above, numeration is wrong when hidden `tab-step-item` exists in an array of items that is passed to a component. 
Screenshot 2022-10-05 at 15 00 50
In the image above, you'll see that hidden step, as fourth element of array is skipped, therefore steps are 3 and 5. We heavily use this in our forms and this bug causes this
Screenshot 2022-10-06 at 10 20 17

### PR DESCRIPTION
**Pull request by predrag-arsic**
Closes #686 

## Acceptance Criteria

- [x] Design Review by @Gagne87, @clastzoo
- [x] Technical Review by @hirsch88, @mladenplaninicic, @nobilo
- [x] [Style Guide](https://stenciljs.com/docs/style-guide) Review @hirsch88, @mladenplaninicic, @nobilo
- [x] Visual test done by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
- [x] Functional test done by @hirsch88, @nobilo, @mladenplaninicic
- Browser Testing by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
    - Desktop
        - [x] Chrome
        - [ ] Edge
        - [x] Safari
        - [ ] Firefox
    - Tablet
        - [ ] iPad (Landscape / Portrait)
    - Mobile
        - [ ] Safari iOS
        - [ ] Chrome Preview

### CODE REVIEW

**Review by nobilo — APPROVED** [review]

**Comment by mladenplaninicic** [comment]
@predrag-arsic tnx for the contribution. I just have one small thing,  in the case when we have a failed step, we need to count that one too. Can you please cover that? Thanks

Screen Shot 2022-10-07 at 11 32 37

File: packages/components/src/components/bal-tabs/components/steps.tsx [hunk 1]
```diff
@@ -80,7 +82,7 @@ export const StepList: FunctionalComponent<TabProps> = ({ value, float, clickabl
                 }}
                 style={{ display: !tab.done ? 'block' : 'none' }}
               >
-                {tab.failed ? '!' : index + 1}
+                {tab.failed ? '!' : tab.hidden ? index : index++}
```
Comment (hirsch88) [inline packages/components/src/components/bal-tabs/components/steps.tsx]: if the step is hidden then don't increase the index, but for the other status increase it 

- normal
- failed
- done

**Review by hirsch88 — CHANGES_REQUESTED** [review]

**Review by mladenplaninicic — APPROVED** [review]

**Review by hirsch88 — APPROVED** [review]
