### PR TITLE
fix(bal-select): click on typeahead field closes the select

### LINKED ISSUE #1018: The close arrow is not working only on typeahead select field
## Detailed description

> When the dropdown is opened, nothing is selected but you want to close the dropdown on the arrow, it is not closed. It can just be closed with clicking outside of the dropdown.

>When you click on the arrow it should close the option list.

> The browser is Chrome

### PR DESCRIPTION
**Pull request by mladenplaninicic**
Closes #1018 

{{short description}}

## Acceptance Criteria

- Design Review by @Gagne87, @clastzoo
- Technical Review by @hirsch88, @mladenplaninicic, @nobilo
- [Style Guide](https://stenciljs.com/docs/style-guide) Review @hirsch88, @mladenplaninicic, @nobilo
- Visual test done by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
- Functional test done by @hirsch88, @nobilo, @mladenplaninicic
- Browser Testing by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
    - Desktop
        - Chrome
        - Edge
        - Safari
        - Firefox
    - Tablet
        - iPad (Landscape / Portrait)
    - Mobile
        - Safari iOS
        - Chrome Preview

### CODE REVIEW

File: packages/components/src/components/form/bal-select/bal-select.tsx [hunk 1]
```diff
@@ -875,14 +875,10 @@ export class Select implements ComponentInterface, Loggable {
       this.focusIndex = -1
       this.balClick.emit(event)
 
-      if (this.typeahead) {
```
Comment (hirsch88) [inline packages/components/src/components/form/bal-select/bal-select.tsx:878]: it should only open on input when it is a typeahead

**Review by hirsch88 — CHANGES_REQUESTED** [review]

File: packages/components/src/components/form/bal-select/bal-select.tsx (hunk 1 above)
Comment (hirsch88) [reply packages/components/src/components/form/bal-select/bal-select.tsx:878]: on typeahead only listen to icon for closing

**Review by hirsch88 — APPROVED** [review]
