### PR TITLE
fix(navigation): adjust mobile behaviour

### LINKED ISSUE #500: [Navigation][Mobile] Bug bucket
### Mobile

Generally - [ ] Pressed State is missing on button is tackeled in another ticket https://github.com/baloise-incubator/design-system/issues/498

**IOS**

- [x] Border Radius on phone-number-overlay is missing. (Only chrome, Safari, Firefox is working)
- [x] Pressed State is missing on buttons respectively is triggered randomly

Image

### #Tablet (Ipad Safari, IOS 15.4.1)

General - [ ] TBD When a tab is opened and the user clicks on the meta navigation, the navigation overlay is closed

- [ ] Spacing is missing to the bottom the last item (Unfallversicherung für Hausangestellte) is cut off.
Image

- [x] The arrow inherits the position of the arrow from the tab before, sometimes it appears randomly behind the the text or far away from the text. 
Image

- [x] If the user jumps from the first tab to the magazine tab which is a link, the overlay is not closing
Image

- [x] The meta navigation gets blocked an is not triggered any more (Chrome), also the icon position bug is visible

https://user-images.githubusercontent.com/62377419/189161037-3f20efd1-4fd8-417f-95e5-cf4b4c1e3281.mp4

**Additional Bugs reported by ibm:** 

 Mobile accordion behaviour
- [x] current: when opening another accordion item the previous ones are still open >> expected: when opening an accordion item the previous open one closes

### PR DESCRIPTION
**Pull request by hirsch88**
Closes #500 

## Acceptance Criteria

- [x] Design Review by @Gagne87, @clastzoo
- [x] Technical Review by @hirsch88, @mladenplaninicic, @nobilo
- Browser Testing by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
    - Desktop
        - [x] Chrome
        - [x] Edge
        - [x] Safari
        - [x] Firefox
    - Tablet
        - [x] iPad (Landscape / Portrait)
    - Mobile
        - [x] Safari iOS
        - [x] Chrome Preview

### CODE REVIEW

**Review by mladenplaninicic — APPROVED** [review]

File: packages/components/src/components/bal-navigation/bal-navigation-popover/bal-navigation-popover.tsx [hunk 1]
```diff
@@ -101,6 +103,43 @@ export class NavigationPopover implements ComponentInterface {
    */
   @Prop() mobileTop = false
 
+  private scrollToTopTimer?: NodeJS.Timer
+  private setActiveTimer?: NodeJS.Timer
+
+  private clearTimeouts() {
+    if (this.scrollToTopTimer) {
+      // console.log('clearTimeout(this.scrollToTopTimer)')
```
Comment (mladenplaninicic) [inline packages/components/src/components/bal-navigation/bal-navigation-popover/bal-navigation-popover.tsx]: - [x] can you please remove this console logs?

**Review by mladenplaninicic — APPROVED** [review]

**Review by nobilo — APPROVED** [review]
