### PR TITLE
fix(number-input): enable dot for a be, de and lu as a decimal number…

### LINKED ISSUE #1217: fix(number-input): check decimal symbol
Use this template if you want to request a breaking change an existing feature.

### Summary

In het numeric data input field the '.' from your numeric keyboard doesn't react as a ','; so where people have to input eg price of their car we show 1800025 euro instead of the 18000,25 euro. Isn't it possible to change the behaviour of the numeric . to a comma seperator in this input field?

> 

#### What is the current proplem to solve?

People input their prices with numeric keyboards as they are used on several sites. They don't review the prices en so we make quotes based on wrong prices (x100).

### PR DESCRIPTION
**Pull request by mladenplaninicic**
Closes #1217 

## Acceptance Criteria

- Design Review by @Gagne87, @clastzoo
- Technical Review by @hirsch88, @mladenplaninicic
- [Style Guide](https://stenciljs.com/docs/style-guide) Review @hirsch88, @mladenplaninicic
- Visual test done by @hirsch88, @mladenplaninicic, @Gagne87, @clastzoo
- Functional test done by @hirsch88, @mladenplaninicic
- Browser Testing by @hirsch88, @mladenplaninicic, @Gagne87, @clastzoo
    - Desktop
        - Chrome
        - Edge
        - Safari
        - Firefox
    - Tablet
        - iPad (Landscape / Portrait)
    - Mobile
        - Safari iOS
        - Chrome Preview

### CODE REVIEW

File: packages/components/src/components/form/bal-number-input/bal-number-input.tsx [hunk 1]
```diff
@@ -65,6 +65,7 @@ export class NumberInput implements ComponentInterface, BalConfigObserver, FormI
   nativeInput?: HTMLInputElement
   inputValue = this.value
   initialValue = 0
+  decimalSeparators = [getDecimalSeparator(), '.']
```
Comment (hirsch88) [inline packages/components/src/components/form/bal-number-input/bal-number-input.tsx]: - [x] needs to be dynamic to be able to react on region or language changes

**Review by hirsch88 — CHANGES_REQUESTED** [review]

**Comment by hirsch88** [comment]
- [x] add changeset

**Review by hirsch88 — APPROVED** [review]

**Comment by hirsch88** [comment]
- [ ] start with , is not working

**Review by hirsch88 — CHANGES_REQUESTED** [review]
- [x] start with , is not working

tested with safari

**Review by hirsch88 — APPROVED** [review]

**Review by hirsch88 — CHANGES_REQUESTED** [review]
- [x] this feature is only for BE, because LU and DE uses the dot as a separator for thousands.

Example 1.000,20

**Review by hirsch88 — APPROVED** [review]
