### PR TITLE
fix(bal-number-input): allow negative numbers

### LINKED ISSUE #985: bal-number-input doesn't allow negative values
## Detailed description

> The input field doesn't seem to allow '-'

> Due to this issue you can't input negative numbers and there doesn't seem to be an attribute that controls it (according to docs)

## Additional information

- Design System Version: 11.0.18 / 12.0.0
- Browser: Chrome 108.0.5359.98 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by mladenplaninicic**
Closes #

{{short description}}

## Acceptance Criteria

- [ ] Design Review by @Gagne87, @clastzoo
- [ ] Technical Review by @hirsch88, @mladenplaninicic, @nobilo
- [ ] [Style Guide](https://stenciljs.com/docs/style-guide) Review @hirsch88, @mladenplaninicic, @nobilo
- [ ] Visual test done by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
- [ ] Functional test done by @hirsch88, @nobilo, @mladenplaninicic
- Browser Testing by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
    - Desktop
        - [ ] Chrome
        - [ ] Edge
        - [ ] Safari
        - [ ] Firefox
    - Tablet
        - [ ] iPad (Landscape / Portrait)
    - Mobile
        - [ ] Safari iOS
        - [ ] Chrome Preview

### CODE REVIEW

File: packages/components/src/components/form/bal-number-input/bal-number-input.tsx [hunk 1]
```diff
@@ -308,7 +314,7 @@ export class NumberInput implements ComponentInterface, BalConfigObserver, FormI
     if (suffix !== '') {
       suffix = ` ${suffix}`
     }
-    return `[0-9${getThousandSeparator()}${this.decimal > 0 ? getDecimalSeparator() : ''}${suffix}]*`
+    return `[-0-9${getThousandSeparator()}${this.decimal > 0 ? getDecimalSeparator() : ''}${suffix}]*`
```
Comment (hirsch88) [inline packages/components/src/components/form/bal-number-input/bal-number-input.tsx]: use getNegativeSymbol here

**Review by hirsch88 — APPROVED** [review]

**Review by hirsch88 — APPROVED** [review]
