### PR TITLE
496 navigationdesktop bug bucket

### LINKED ISSUE #496: [Navigation][Desktop] Bug bucket
Following bugs were found by me testing the navigation on Desktop on my Macbook 16" on Chrome, Safari & Edge: 

- [x] Stage disappears behind main navigation >> back button not visible anymore

- [x] Scrolling enabled while having a dialogue open >> should not be possible

Please compare to the attachments. 

Screenshot 2022-09-07 at 11 46 39

https://user-images.githubusercontent.com/29020214/189086752-5fd83a81-ac31-4e77-937f-29b0fddcd9cd.mov

Additional bugs reported by ibm: 

Menu with much content 
- [x] current: No margin above logo >> **expected:** Logo should have margin
- [x] current: No Linebreak at Menue items >> **expected:** There should be a line break if the menue items are too long

Image

- [x] No item limit (tabs). Should be limited to 7 according to ACs

- [x] Safari 15.6.1: When navigation through menue items with different length of overview link label, the arrow will stay at the position of the first opened menu item

Image

### PR DESCRIPTION
**Pull request by hirsch88**
Closes #496 

## Acceptance Criteria

- [x] Design Review by @Gagne87, @clastzoo
- [x] Technical Review by @hirsch88, @mladenplaninicic, @nobilo
- Browser Testing by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
    - Desktop
        - [x] Chrome
        - [x] Edge
        - [x] Safari
        - [x] Firefox
    - Tablet
        - [ ] iPad (Landscape / Portrait)
    - Mobile
        - [ ] Safari iOS
        - [ ] Chrome Preview

### CODE REVIEW

File: packages/components/src/components/notice/bal-modal/bal-modal.tsx [hunk 1]
```diff
@@ -242,21 +245,23 @@ export class Modal implements OverlayInterface {
...
 
   private setModalActiveOnBody() {
-    if (document && document.documentElement && !document.documentElement.classList.contains('bal-modal-active')) {
-      document.documentElement.classList.add('bal-modal-active')
-    }
-    if (document && document.body && !document.body.classList.contains('bal-modal-active')) {
-      document.body.classList.add('bal-modal-active')
-    }
+    this.bodyScrollBlocker.block()
+    // if (document && document.documentElement && !document.documentElement.classList.contains('bal-modal-active')) {
```
Comment (mladenplaninicic) [inline packages/components/src/components/notice/bal-modal/bal-modal.tsx]: - [x] can you remove these comments?

File: packages/components/src/stories/assets/css/theme.css [hunk 2]
```diff
@@ -1,6 +1,6 @@
 html {
-  scroll-behavior: smooth !important;
-  scroll-padding-top: 64px !important;
+  /* scroll-behavior: smooth !important; */
```
Comment (mladenplaninicic) [inline packages/components/src/stories/assets/css/theme.css]: - [x] these too?

File: packages/components/src/components/bal-popover/bal-popover.sass [hunk 3]
```diff
@@ -32,16 +36,11 @@
   +element(content)
     display: none
     z-index: 20
-    min-width: 260px
     box-shadow: var(--bal-shadow)
     background: var(--bal-color-white)
-    padding: 1rem
-    +tablet
-      padding: 1.5rem
+    min-width: 260px
```
Comment (mladenplaninicic) [inline packages/components/src/components/bal-popover/bal-popover.sass]: - [x] can you use rem here?

**Review by mladenplaninicic — APPROVED** [review]
