### PR TITLE
fix(): verify if window object exist when checking if current browser…

### LINKED ISSUE #669: SSR build failure since DS version 10.23.0
## Detailed description

Since updating our projects to use design system version 10.23.0 (and beyond) we are unable to build any project.
I pasted the related error below.

My guess since it's giving a `navigator is not defined` error, this is related to SSR.
Make sure anywhere the `window` object is used, there is check to see if window is defined.

## Console error

 ERROR

There was an error compiling the html.js component for the development server.
See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html ReferenceError:
navigator is not defined

> 1 | var isSafari=/^((?!chrome|android).)*safari/i.test(navigator.userAgent);var
isBrowser=function(r){if(r==="Safari"){return isSafari}return false};export{isBrowser as i};
    | ^

  WebpackError: ReferenceError: navigator is not defined

  - browser-b3352a1d.js:1
    [baloise]/[@baloise]/design-system-next-components/dist/esm-es5/browser-b3352a1d.js:1:1

  - bootstrap:19
    baloise/webpack/bootstrap:19:1

  - PropertyAddress.tsx:141
    baloise/src/templates/PropertyAddress.tsx:141:29

  - bootstrap:19
    baloise/webpack/bootstrap:19:1

  - url-state-machine.js:264
    [baloise]/[whatwg-url]/lib/url-state-machine.js:264:1

  - bootstrap:19
    baloise/webpack/bootstrap:19:1

  - index.js:14
    [baloise]/[filter-obj]/index.js:14:1

  - bootstrap:19
    baloise/webpack/bootstrap:19:1

  - bootstrap:19
    baloise/webpack/bootstrap:19:1

  - bootstrap:19
    baloise/webpack/bootstrap:19:1

  - bootstrap:19
    baloise/webpack/bootstrap:19:1

  - api-runner-ssr.js:15
    baloise/.cache/api-runner-ssr.js:15:15

  - bootstrap:19
    baloise/webpack/bootstrap:19:1

not finished Building development bundle - 10.170s

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### PR DESCRIPTION
**Pull request by mladenplaninicic**
… is Safari

Closes #

{{short description}}

## Acceptance Criteria

- [ ] Design Review by @Gagne87, @clastzoo
- [x] Technical Review by @hirsch88, @mladenplaninicic, @nobilo
- [ ] [Style Guide](https://stenciljs.com/docs/style-guide) Review @hirsch88, @mladenplaninicic, @nobilo
- [ ] Visual test done by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
- [ ] Functional test done by @hirsch88, @nobilo, @mladenplaninicic
- Browser Testing by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
    - Desktop
        - [ ] Chrome
        - [ ] Edge
        - [ ] Safari
        - [ ] Firefox
    - Tablet
        - [ ] iPad (Landscape / Portrait)
    - Mobile
        - [ ] Safari iOS
        - [ ] Chrome Preview

### CODE REVIEW

File: packages/components/src/utils/browser.ts [hunk 1]
```diff
@@ -1,10 +1,18 @@
...
 export const isBrowser = (browser: Browser): boolean => {
   if (browser === 'Safari') {
     return isSafari
   }
   return false
 }
+
+function getUserAgent(): string {
+  if (typeof (window as any) !== 'undefined' && window?.navigator && navigator?.userAgent) {
+    return navigator.userAgent
```
Comment (nobilo) [inline packages/components/src/utils/browser.ts]: maybe you can write something like this: 
`    return navigator.userAgent ?? '' `
can we use here nullish coalescing operator:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator

Comment (mladenplaninicic) [reply packages/components/src/utils/browser.ts]: yes, changed

**Review by nobilo — APPROVED** [review]
