### PR TITLE
Fix/bal modal

### LINKED ISSUE #806: <bal-modal> isClosable property does not work
## Title line template: [Title]
If I pass isCloasble: false I would expext that the little 'x' on the top right corner is not there, but it is and the modal is still closable with this little button. 

## Steps to reproduce the issue

1. Use <bal-modal> with isClosable:false 
2. Open modal, press little 'x' button in top right corner

It's also not working in the storybook: https://design-system-next.vercel.app/?path=/story/components-notice-modal--basic&args=isClosable:false

Thanks for fixing it :)

### PR DESCRIPTION
**Pull request by nobilo**
Closes #806

{{short description}}

## Acceptance Criteria

- [ ] Design Review by @Gagne87, @clastzoo
- [ ] Technical Review by @hirsch88, @mladenplaninicic, @nobilo
- [ ] [Style Guide](https://stenciljs.com/docs/style-guide) Review @hirsch88, @mladenplaninicic, @nobilo
- [ ] Visual test done by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
- [ ] Functional test done by @hirsch88, @nobilo, @mladenplaninicic
- Browser Testing by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
    - Desktop
        - [ ] Chrome
        - [ ] Edge
        - [ ] Safari
        - [ ] Firefox
    - Tablet
        - [ ] iPad (Landscape / Portrait)
    - Mobile
        - [ ] Safari iOS
        - [ ] Chrome Preview

### CODE REVIEW

File: packages/components/src/components/notice/bal-modal/bal-modal-header/bal-modal-header.tsx [hunk 1]
```diff
@@ -26,7 +26,14 @@ export class ModalHeader {
             <slot></slot>
           </h2>
         </div>
-        <bal-close class="bal-modal__header__close data-test-modal-close" onClick={this.closeHandler}></bal-close>
+        <bal-close
```
Comment (hirsch88) [inline packages/components/src/components/notice/bal-modal/bal-modal-header/bal-modal-header.tsx]: - [x] use a conditional rendering and not css to avoid to print to much to the DOM

**Review by hirsch88 — CHANGES_REQUESTED** [review]

**Review by mladenplaninicic — APPROVED** [review]

**Review by hirsch88 — APPROVED** [review]
