### PR TITLE
fix(hint): add popover for tablet and desktop

### LINKED ISSUE #297: Bal-Hint component ignores screen size
Yesterday we saw in the UX review we had with Belgium, that hints are not displayed correctly when the screen size is too small (compare to screenshot > 2/3 of the content is not shown anymore).

**Expected behaviour:**  Fly-out of the hint re-shuffled in a way that the whole content is readable by the user (e.g. opened in a new row, right aligned with the info icon).

@Gery mentioned that he might already have a solution for it. 

Thanks for taking care.  

Image

### PR DESCRIPTION
**Pull request by hirsch88**

### CODE REVIEW

File: packages/components/src/components/bal-hint/bal-hint.tsx [hunk 1]
```diff
@@ -77,27 +60,27 @@ export class Hint implements BalConfigObserver {
...
-  }
-
   /**
    * Toggles the hint box.
    */
   @Method()
   async toggle(): Promise<void> {
-    this.calcIsDropDownContentUp()
-    this.isActive = !this.isActive
+    console.log('toggle', this.isActive)
```
Comment (nobilo) [inline packages/components/src/components/bal-hint/bal-hint.tsx]: i guess left over, maybe to remove it :) ?

File: packages/components/src/components/bal-hint/bal-hint.tsx [hunk 2]
```diff
@@ -77,27 +60,27 @@ export class Hint implements BalConfigObserver {
...
+    if (this.isActive) {
+      this.dismiss()
```
Comment (nobilo) [inline packages/components/src/components/bal-hint/bal-hint.tsx:69]: should we toggle `this.isActive` variable here as well?

File: packages/components/src/components/bal-popover/bal-popover.sass [hunk 3]
```diff
@@ -7,6 +7,16 @@
...
+  +modifier(hint)
+    .bal-popover__content
+      +mobile
+        min-height: 100vh
+        .bal-popover__content__inner
+          min-height: 100vh
+      +tablet
+        max-width: 320px
+      +desktop
+        max-width: 464px
```
Comment (nobilo) [inline packages/components/src/components/bal-popover/bal-popover.sass]: why exactly 464px, should we use some relative sizing unit here instead of px maybe?

**Review by nobilo — CHANGES_REQUESTED** [review]

File: packages/components/src/components/bal-hint/bal-hint.tsx (hunk 2 above)
Comment (nobilo) [reply packages/components/src/components/bal-hint/bal-hint.tsx:69]: ah i see it is toggling inside the methods...

**Review by nobilo — APPROVED** [review]
