### PR TITLE
Fix/angular inital load

### LINKED ISSUE #603: Initial value does not get set on remote typeahead when multiple remote typeaheads are displayed
The setting of a initial value of the remote typeaheads do not work when multiple remote typeaheads are displayed on one page. 

I provided an example branch with the name (feat/remote_typeahead_initialization_bug) in this [repository](https://github.com/baloise/design-system-examples).

On initial run of the application sometimes it works. But when you do a reload of the page it does not work anymore.

Hint:

I did a small analysis and could be that this function is the reason for the issue:

```
 updateInputValue(value) {
    if (this.updateInputValueTimer) {
      clearTimeout(this.updateInputValueTimer);
    }
    this.updateInputValueTimer = setTimeout(() => {
      if (!lodash_isnil(this.inputElement)) {
        this.inputElement.value = value;
        this.inputValue = value;
      }
    }, 0);
  }

```
since it uses timeoutes maybe it is a timing issue.

### PR DESCRIPTION
**Pull request by hirsch88**
Closes #603

## Acceptance Criteria

- [ ] Design Review by @Gagne87, @clastzoo
- [ ] Technical Review by @hirsch88, @mladenplaninicic, @nobilo
- [ ] [Style Guide](https://stenciljs.com/docs/style-guide) Review @hirsch88, @mladenplaninicic, @nobilo
- [ ] Visual test done by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
- [ ] Functional test done by @hirsch88, @nobilo, @mladenplaninicic
- Browser Testing by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
    - Desktop
        - [ ] Chrome
        - [ ] Edge
        - [ ] Safari
        - [ ] Firefox
    - Tablet
        - [ ] iPad (Landscape / Portrait)
    - Mobile
        - [ ] Safari iOS
        - [ ] Chrome Preview

### CODE REVIEW

**Review by mladenplaninicic — APPROVED** [review]

**Review by nobilo — APPROVED** [review]

File: packages/components/src/components/form/bal-select/bal-select.tsx [hunk 1]
```diff
@@ -723,7 +721,7 @@ export class Select {
   }
 
   private syncNativeInput() {
-    if (!this.multiple && !this.remote) {
+    if (!this.multiple) {
```
Comment (nobilo) [inline packages/components/src/components/form/bal-select/bal-select.tsx:724]: shouldn't we also sync if it is multiple? is it done as well ?

**Review by nobilo — CHANGES_REQUESTED** [review]

File: packages/components/src/components/form/bal-select/bal-select.tsx (hunk 1 above)
Comment (hirsch88) [reply packages/components/src/components/form/bal-select/bal-select.tsx:724]: because the value is not presented in the native input for multiple
