### PR TITLE
574 bal snackbar message has a wrong font size

### LINKED ISSUE #574: [bal-snackbar] message has a wrong font size
actual font size: 16px
expected font size: 12px

### PR DESCRIPTION
**Pull request by hirsch88**
## Acceptance Criteria

- [ ] Design Review by @Gagne87, @clastzoo
- [ ] Technical Review by @hirsch88, @mladenplaninicic, @nobilo
- [ ] Visual test done by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
- [ ] Functional test done by @hirsch88, @nobilo, @mladenplaninicic
- Browser Testing by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
    - Desktop
        - [ ] Chrome
        - [ ] Edge
        - [ ] Safari
        - [ ] Firefox
    - Tablet
        - [ ] iPad (Landscape / Portrait)
    - Mobile
        - [ ] Safari iOS
        - [ ] Chrome Preview

### CODE REVIEW

File: packages/components/src/components/bal-hint/bal-hint-title/bal-hint-title.tsx [hunk 1]
```diff
@@ -17,16 +17,27 @@ export class HintTitle {
...
+            'title': true,
+            'is-3': true,
           }}
-          level="h4"
+        >
+          <span>
+            <slot></slot>
+          </span>
+        </h3>
+        {/* <bal-heading
```
Comment (mladenplaninicic) [inline packages/components/src/components/bal-hint/bal-hint-title/bal-hint-title.tsx]: can you remove this comment?

**Review by mladenplaninicic — APPROVED** [review]

File: packages/components/src/components/bal-hint/bal-hint-title/bal-hint-title.tsx (hunk 1 above)
Comment (hirsch88) [reply packages/components/src/components/bal-hint/bal-hint-title/bal-hint-title.tsx]: done
